[workspace]
members = ["configuration", "provider-presets"]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.97.1"
publish = false

[workspace.dependencies]
philo = { path = "../.." }
philo-config = { path = "../../crates/philo-config" }
philo-presets = { path = "../../crates/philo-presets" }
